### ISSUE TITLE
Dear author, could you share the dataset in program, thank you very much:)

### ISSUE THREAD

**Issue by lidayuls** [dilara91/sentiment_analysis#1]
This is my email：949007264@.com    thank you very much:)

**Comment by dilarakkl** [comment]
Hi there!
This analysis was done on the dataset of the Semeval Challenge. You can find the tweets to download from here. https://www.cs.york.ac.uk/semeval-2013/task2/index.php%3Fid=data.html

**Comment by lidayuls** [comment]
I've tried it, but failed, hope you upload the dataset and lexicons, or data format description.Best Wishes~

**Comment by dilarakkl** [comment]
Hi. I also don't have the raw data, I've got the preprocessed one. You can get the twitter data from the .tsv files by using the scripts Semeval provides. Here is a part of README for Semeval 2013 Task2, 
"DOWNLOAD
The distribution consists of a set of twitter status IDs, with annotations.  
In order to address privacy concerns, rather than releasing the original Tweets, 
we are providing a python script that downloads the data.  This is similar 
to the mechanism for distributing Twitter data used in the TREC Microblog track.
The download script works for both tasks, and can be used like this:
    	easy_install beautifulsoup4
	python download_tweets.py input_file > output_file
Where the output file contains the text of the Tweets in addition to annotations.
In cases where the Tweet is no longer available, rather then including the text 
of the Tweet, the script outputs "Not Available".
"
